# -*- coding: utf-8 -*-
"""OpenNMT-py- SEQ-SEQ.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1IyeukY6tZI8owG1uTMKcA-Gxp3WHcX3_
"""

from google.colab import drive
drive.mount('/content/drive')

cd /content/drive/MyDrive/OpenNMT-py-1.2.0/OpenNMT-py-1.2.0

!pip install -qq -e .
!pip install -qq textstat
!pip install -qq python-Levenshtein

!python  /content/drive/MyDrive/OpenNMT-py-1.2.0/OpenNMT-py-1.2.0/preprocess.py -train_src '/content/drive/MyDrive/Simplification/Data/NewWikiClean_src.txt' \
-train_tgt '/content/drive/MyDrive/Simplification/Data/NewWikiClean_tgt.txt'  \
-valid_src '/content/drive/MyDrive/Simplification/Data/Val_nisioi_src.txt' \
-valid_tgt '/content/drive/MyDrive/Simplification/Data/Val_nisioi_tgt.txt' \
-share_vocab -save_data '/content/drive/MyDrive/OPENNMT-1.20/Model/new'

#!python /usr/local/lib/python3.6/dist-packages/onmt/bin/train.py -h

!python  /content/drive/MyDrive/OpenNMT-py-1.2.0/OpenNMT-py-1.2.0/train.py -data '/content/drive/MyDrive/OPENNMT-1.20/Model/new' \
-save_model '/content/drive/MyDrive/OPENNMT-1.20/NEW_WIKI/'  -gpu_ranks 0 \
-world_size 1 -train_steps 60000 \
-valid_steps 5000 -early_stopping 2 \
-max_grad_norm 5 -dropout 0.3 \
-feat_vec_size 20 -word_vec_size 500 -share_embeddings \
-share_decoder_embeddings -model_type text \
-encoder_type rnn -rnn_type LSTM -layers 2 \
-rnn_size 500 -global_attention general \
-learning_rate_decay 0.7

!python /content/drive/MyDrive/OPENNMT-1.20/OpenNMT-py-1.2.0/translate.py -model '/content/drive/MyDrive/OPENNMT-1.20/NEW_WIKI/_step_20000.pt' \
-src '/content/drive/MyDrive/OPENNMT-1.20/test_uni.en' \
 -output '/content/drive/MyDrive/OPENNMT-1.20/Data/pred_single_dummy_30000.txt' -n_best 4 -beam_size 5 -replace_unk -gpu 0

test_path = '/content/drive/MyDrive/OPENNMT-1.20/Data/test.en'
references_path = '/content/drive/MyDrive/OPENNMT-1.20/test_references.tsv'
prediction_path = '/content/drive/MyDrive/OPENNMT-1.20/Data/pred_single_dummy_30000.txt'
#prediction_path = '/content/drive/MyDrive/OPENNMT-1.20/Data/turk_test_out.txt'

#bart_path = '/content/drive/MyDrive/Simplification/BART_MODELS/BART_gen.txt'

!python /content/drive/MyDrive/OPENNMT-1.20/evaluate.py  $test_path $references_path $prediction_path $4

!python '/content/drive/MyDrive/Simplification/SARI_org.py' -c '/content/drive/MyDrive/OPENNMT-1.20/test_uni.en' \
-r '/content/drive/MyDrive/Simplification/Data/TestData/TestRefs' \
-s '/content/drive/MyDrive/OPENNMT-1.20/Data/pred_single_dummy_30000.txt_h3'



!python /content/drive/MyDrive/OPENNMT-1.20/OpenNMT-py-1.2.0/translate.py -model '/content/drive/MyDrive/OPENNMT-1.20/NEW_WIKI/_step_35000.pt' \
-src '/content/drive/MyDrive/Simplification/Data/TestData/AssetTest.orig' \
 -output '/content/drive/MyDrive/OPENNMT-1.20/Data/pred_single_dummy_30000.txt' -n_best 4 -beam_size 5 -replace_unk -gpu 0

!python '/content/drive/MyDrive/Simplification/SARI_org.py' -c '/content/drive/MyDrive/Simplification/Data/TestData/AssetTest.orig' \
-r '/content/drive/MyDrive/Simplification/Data/TestData/AssetRefs' \
-s '/content/drive/MyDrive/OPENNMT-1.20/Data/asset_test_out.txt'

